### PR TITLE
add input subscribe event, update bar_status_event to bar_state_event

### PR DESCRIPTION
**Pull request by ghost**
One question tho, does `XKBActiveLayoutName  *string` have to be a **pointer** to a string? Why not just a string?

### CODE REVIEW

**Comment by joshuarubin** [comment]
Hey, so sorry for the delay! Thank you so much for contributing!!!
First, is there a way that we can deprecate the removed functions so that we don't break existing code that depends on those methods?
Then, as far as your question, I think a string is ok, why do you think it has to be a pointer?

**Comment by ghost** [comment]
> First, is there a way that we can deprecate the removed functions so that we don't break existing code that depends on those methods?

Not sure what you are referring to here, but my commit does not break any existing code that was working. If you mean renaming of `bar_status_update` to `bar_state_update` - that happened in the protocol itself and as such, code using `bar_status_update` (such as `processEvent` function) was not working properly anyway.


> Then, as far as your question, I think a string is ok, why do you think it has to be a pointer?

No, i don't think it has to be a pointer, that's why i'm asking you! There are places where the json unmarshals into a string pointer instead of a string (see `XKBActiveLayoutName` in `type Input struct`). I didn't change it so as to not break anything important, but i don't think it's needed anyway, so i don't see why you wouldn't change it to just use string.

**Comment by joshuarubin** [comment]
Ah, you're right about the breaking changes, I misread that. I think this is all fine. If you want to change the strings, go ahead.

**Comment by ghost** [comment]
> Ah, you're right about the breaking changes, I misread that. I think this is all fine. If you want to change the strings, go ahead.

Well, now that you said that, i actually looked into why you made them pointers in the first place, and that's because sometimes it might be missing from the JSON object, so it would be better to have it as nil instead of an empty string.

That said, i added further documentation from the man page and updated objects to the latest version. Compiles fine, i think you can merge it.

**Comment by joshuarubin** [comment]
Wow, this looks fantastic! Good call about being able to represent null values in json too. And the documentation... :chefs_kiss:

I'm still worried about this being an api breaking change though. Code might have references to things like `BarStatusUpdateEvent` which no longer exist. I understand they don't exist in the sway api either, but we might still want to keep them and just mark them as deprecated for some time. I recognize this is still a 0.x.y release, but it probably should have been considered a 1.x.y release and this change would have necessitated bumping the major version number.

**Comment by ghost** [comment]
Sure, this looks good to you?

**Review by joshuarubin — APPROVED** [review]
Looks great! Thanks so much for your contribution!

**Pull request merged**
