### PR TITLE
add a function to traverse  nodes

### PR DESCRIPTION
**Pull request by smoka7**

### CODE REVIEW

**Review by joshuarubin — APPROVED** [review]
Looks great! Thanks for contributing

**Comment by smoka7** [comment]
Happy to Help.
By the way `opt = "altwin:ctrl_win"` in this [line](https://github.com/joshuarubin/go-sway/blob/470ebafea46471a5faf7e862f9587e32d782e19e/sway_test.go#L144) breaks the user layout. Could you reverted at the end of test?

**Comment by joshuarubin** [comment]
Is there a way to determine the previous value?

**Comment by smoka7** [comment]
I couldn't find a way to get `xkb_options` value but you can use `xkb_layout` instead and gets the old value from `getInputs()` .

**Pull request merged**
